
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Wed Nov 19 19:51:31 CET 2025
//----------------------------------------------------

package constructorast;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int PCIERRE = 13;
  public static final int IGUALIGUAL = 10;
  public static final int ELSE = 3;
  public static final int IGUAL = 9;
  public static final int TIPO_HUGEHUGE = 22;
  public static final int TIPO_HUGE = 21;
  public static final int IDEN = 17;
  public static final int CCIERRE = 15;
  public static final int TRUE = 5;
  public static final int IF = 2;
  public static final int HUGE = 19;
  public static final int CAP = 14;
  public static final int HUGEHUGE = 20;
  public static final int MAYOR = 11;
  public static final int EOF = 0;
  public static final int TIPO_BOOL = 7;
  public static final int PAP = 12;
  public static final int FALSE = 6;
  public static final int error = 1;
  public static final int TIPO_ENT = 4;
  public static final int PUNTOCOMA = 16;
  public static final int ENT = 18;
  public static final int MAS = 8;
  public static final int MULTIPLICA = 23;
}

