
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Fri Dec 05 13:48:16 CET 2025
//----------------------------------------------------

package constructorast;

import java_cup.runtime.*;
import alex.AnalizadorLexicoTiny;
import alex.UnidadLexica;
import alex.TokenValue;
import errors.GestionErroresTiny;
import ast.*;
import java.util.LinkedList;
import java_cup.runtime.ComplexSymbolFactory.Location;

/** CUP v0.11b beta 20140220 generated parser.
  * @version Fri Dec 05 13:48:16 CET 2025
  */
public class ConstructorAST extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public ConstructorAST() {super();}

  /** Constructor which sets the default scanner. */
  public ConstructorAST(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ConstructorAST(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\033\000\002\002\003\000\002\002\004\000\002\003" +
    "\004\000\002\003\002\000\002\005\003\000\002\005\003" +
    "\000\002\005\003\000\002\007\006\000\002\010\005\000" +
    "\002\010\005\000\002\010\005\000\002\010\005\000\002" +
    "\006\012\000\002\004\006\000\002\011\005\000\002\011" +
    "\003\000\002\012\005\000\002\012\003\000\002\013\005" +
    "\000\002\013\003\000\002\015\005\000\002\015\003\000" +
    "\002\014\003\000\002\014\003\000\002\014\003\000\002" +
    "\014\003\000\002\014\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\070\000\020\002\ufffe\004\014\006\015\011\016\012" +
    "\013\013\011\030\010\001\002\000\022\002\ufffd\004\ufffd" +
    "\006\ufffd\011\ufffd\012\ufffd\013\ufffd\023\ufffd\030\ufffd\001" +
    "\002\000\022\002\ufffc\004\ufffc\006\ufffc\011\ufffc\012\ufffc" +
    "\013\ufffc\023\ufffc\030\ufffc\001\002\000\022\002\ufffb\004" +
    "\ufffb\006\ufffb\011\ufffb\012\ufffb\013\ufffb\023\ufffb\030\ufffb" +
    "\001\002\000\004\002\001\001\002\000\004\015\070\001" +
    "\002\000\004\030\066\001\002\000\004\002\065\001\002" +
    "\000\004\030\063\001\002\000\004\020\025\001\002\000" +
    "\004\030\023\001\002\000\004\030\021\001\002\000\022" +
    "\002\ufffe\004\014\006\015\011\016\012\013\013\011\023" +
    "\ufffe\030\010\001\002\000\006\002\uffff\023\uffff\001\002" +
    "\000\004\024\022\001\002\000\022\002\ufff8\004\ufff8\006" +
    "\ufff8\011\ufff8\012\ufff8\013\ufff8\023\ufff8\030\ufff8\001\002" +
    "\000\004\024\024\001\002\000\022\002\ufff9\004\ufff9\006" +
    "\ufff9\011\ufff9\012\ufff9\013\ufff9\023\ufff9\030\ufff9\001\002" +
    "\000\014\007\030\010\032\020\027\030\031\031\026\001" +
    "\002\000\016\014\uffeb\016\uffeb\017\uffeb\021\uffeb\024\uffeb" +
    "\025\uffeb\001\002\000\014\007\030\010\032\020\027\030" +
    "\031\031\026\001\002\000\016\014\uffea\016\uffea\017\uffea" +
    "\021\uffea\024\uffea\025\uffea\001\002\000\016\014\uffe8\016" +
    "\uffe8\017\uffe8\021\uffe8\024\uffe8\025\uffe8\001\002\000\016" +
    "\014\uffe9\016\uffe9\017\uffe9\021\uffe9\024\uffe9\025\uffe9\001" +
    "\002\000\016\014\uffee\016\uffee\017\uffee\021\uffee\024\uffee" +
    "\025\057\001\002\000\016\014\uffec\016\uffec\017\uffec\021" +
    "\uffec\024\uffec\025\uffec\001\002\000\014\014\ufff0\016\055" +
    "\017\ufff0\021\ufff0\024\ufff0\001\002\000\012\014\ufff2\017" +
    "\053\021\ufff2\024\ufff2\001\002\000\006\014\040\021\041" +
    "\001\002\000\014\007\030\010\032\020\027\030\031\031" +
    "\026\001\002\000\004\022\042\001\002\000\020\004\014" +
    "\006\015\011\016\012\013\013\011\023\ufffe\030\010\001" +
    "\002\000\004\023\044\001\002\000\004\005\045\001\002" +
    "\000\004\022\047\001\002\000\022\002\ufff5\004\ufff5\006" +
    "\ufff5\011\ufff5\012\ufff5\013\ufff5\023\ufff5\030\ufff5\001\002" +
    "\000\020\004\014\006\015\011\016\012\013\013\011\023" +
    "\ufffe\030\010\001\002\000\004\023\051\001\002\000\022" +
    "\002\ufff4\004\ufff4\006\ufff4\011\ufff4\012\ufff4\013\ufff4\023" +
    "\ufff4\030\ufff4\001\002\000\012\014\ufff3\017\053\021\ufff3" +
    "\024\ufff3\001\002\000\014\007\030\010\032\020\027\030" +
    "\031\031\026\001\002\000\014\014\ufff1\016\055\017\ufff1" +
    "\021\ufff1\024\ufff1\001\002\000\014\007\030\010\032\020" +
    "\027\030\031\031\026\001\002\000\016\014\uffef\016\uffef" +
    "\017\uffef\021\uffef\024\uffef\025\057\001\002\000\014\007" +
    "\030\010\032\020\027\030\031\031\026\001\002\000\016" +
    "\014\uffed\016\uffed\017\uffed\021\uffed\024\uffed\025\uffed\001" +
    "\002\000\006\014\040\021\062\001\002\000\016\014\uffe7" +
    "\016\uffe7\017\uffe7\021\uffe7\024\uffe7\025\uffe7\001\002\000" +
    "\004\024\064\001\002\000\022\002\ufff7\004\ufff7\006\ufff7" +
    "\011\ufff7\012\ufff7\013\ufff7\023\ufff7\030\ufff7\001\002\000" +
    "\004\002\000\001\002\000\004\024\067\001\002\000\022" +
    "\002\ufff6\004\ufff6\006\ufff6\011\ufff6\012\ufff6\013\ufff6\023" +
    "\ufff6\030\ufff6\001\002\000\014\007\030\010\032\020\027" +
    "\030\031\031\026\001\002\000\006\014\040\024\072\001" +
    "\002\000\022\002\ufffa\004\ufffa\006\ufffa\011\ufffa\012\ufffa" +
    "\013\ufffa\023\ufffa\030\ufffa\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\070\000\016\002\011\003\006\005\016\006\003\007" +
    "\004\010\005\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\014\003" +
    "\017\005\016\006\003\007\004\010\005\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\014\011\036\012\035\013\034" +
    "\014\033\015\032\001\001\000\002\001\001\000\014\011" +
    "\060\012\035\013\034\014\033\015\032\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\012\012\051\013\034\014\033\015" +
    "\032\001\001\000\002\001\001\000\014\003\042\005\016" +
    "\006\003\007\004\010\005\001\001\000\002\001\001\000" +
    "\004\004\045\001\001\000\002\001\001\000\002\001\001" +
    "\000\014\003\047\005\016\006\003\007\004\010\005\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\013\053\014\033\015\032\001\001\000\002\001" +
    "\001\000\006\014\033\015\055\001\001\000\002\001\001" +
    "\000\004\014\057\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\014\011\070\012\035\013\034\014\033\015\032\001\001" +
    "\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ConstructorAST$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ConstructorAST$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ConstructorAST$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {
 
   errores = new GestionErroresTiny();
   AnalizadorLexicoTiny alex = (AnalizadorLexicoTiny)getScanner();
   alex.fijaGestionErrores(errores);

    }

  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {
 return getScanner().next_token(); 
    }

 
   private GestionErroresTiny errores;
   public void syntax_error(Symbol unidadLexica) {
     errores.errorSintactico((UnidadLexica)unidadLexica);
   }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$ConstructorAST$actions {
  private final ConstructorAST parser;

  /** Constructor */
  CUP$ConstructorAST$actions(ConstructorAST parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ConstructorAST$do_action_part00000000(
    int                        CUP$ConstructorAST$act_num,
    java_cup.runtime.lr_parser CUP$ConstructorAST$parser,
    java.util.Stack            CUP$ConstructorAST$stack,
    int                        CUP$ConstructorAST$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ConstructorAST$result;

      /* select the action based on the action number */
      switch (CUP$ConstructorAST$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // P ::= LInst 
            {
              LinkedList<Instruccion> RESULT =null;
		LinkedList<Instruccion> l = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = l; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("P",0, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= P EOF 
            {
              Object RESULT =null;
		LinkedList<Instruccion> start_val = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		RESULT = start_val;
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("$START",0, RESULT);
            }
          /* ACCEPT */
          CUP$ConstructorAST$parser.done_parsing();
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // LInst ::= Inst LInst 
            {
              LinkedList<Instruccion> RESULT =null;
		Instruccion inst = (Instruccion)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		LinkedList<Instruccion> l = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 l.addFirst(inst);
               RESULT = l;
            
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("LInst",1, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // LInst ::= 
            {
              LinkedList<Instruccion> RESULT =null;
		 RESULT = new LinkedList(); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("LInst",1, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // Inst ::= Cond 
            {
              Instruccion RESULT =null;
		Instruccion inst = (Instruccion)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = inst; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Inst",3, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // Inst ::= Asig 
            {
              Instruccion RESULT =null;
		Instruccion inst = (Instruccion)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = inst; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Inst",3, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // Inst ::= Decl 
            {
              Instruccion RESULT =null;
		Instruccion inst = (Instruccion)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = inst; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Inst",3, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // Asig ::= IDEN IGUAL E0 PUNTOCOMA 
            {
              Instruccion RESULT =null;
		TokenValue id = (TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-3)).value;
		E exp = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		 RESULT = new Asignacion(id.lexema, exp); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Asig",5, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // Decl ::= TIPO_ENT IDEN PUNTOCOMA 
            {
              Instruccion RESULT =null;
		TokenValue id = (TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		 RESULT = new Declaracion(Type.NUM, id.lexema); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Decl",6, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // Decl ::= TIPO_BOOL IDEN PUNTOCOMA 
            {
              Instruccion RESULT =null;
		TokenValue id = (TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		 RESULT = new Declaracion(Type.BOOL, id.lexema); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Decl",6, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // Decl ::= TIPO_HUGE IDEN PUNTOCOMA 
            {
              Instruccion RESULT =null;
		TokenValue id = (TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		 RESULT = new Declaracion(Type.HUGE, id.lexema); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Decl",6, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // Decl ::= TIPO_HUGEHUGE IDEN PUNTOCOMA 
            {
              Instruccion RESULT =null;
		TokenValue id = (TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		 RESULT = new Declaracion(Type.HUGEHUGE, id.lexema); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Decl",6, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // Cond ::= IF PAP E0 PCIERRE CAP LInst CCIERRE ElseCase 
            {
              Instruccion RESULT =null;
		E exp = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-5)).value;
		LinkedList<Instruccion> inst_if = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		LinkedList<Instruccion> inst_else = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new Condicional(exp, inst_if, inst_else); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Cond",4, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // ElseCase ::= ELSE CAP LInst CCIERRE 
            {
              LinkedList<Instruccion> RESULT =null;
		LinkedList<Instruccion> l = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		 RESULT = l; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("ElseCase",2, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // E0 ::= E0 MAS E1 
            {
              E RESULT =null;
		E op1 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		E op2 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new EBin(BinOps.MAS, op1, op2); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("E0",7, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // E0 ::= E1 
            {
              E RESULT =null;
		E exp = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = exp; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("E0",7, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // E1 ::= E1 MAYOR E2 
            {
              E RESULT =null;
		E op1 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		E op2 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new EBin(BinOps.MAYOR, op1, op2); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("E1",8, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // E1 ::= E2 
            {
              E RESULT =null;
		E exp = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = exp; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("E1",8, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // E2 ::= E2 IGUALIGUAL E4 
            {
              E RESULT =null;
		E op1 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		E op2 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new EBin(BinOps.IGUAL, op1, op2); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("E2",9, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // E2 ::= E4 
            {
              E RESULT =null;
		E exp = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = exp; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("E2",9, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // E4 ::= E4 MULTIPLICA E3 
            {
              E RESULT =null;
		E op1 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		E op2 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new EBin(BinOps.MULTIPLICA, op1, op2); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("E4",11, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // E4 ::= E3 
            {
              E RESULT =null;
		E exp = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = exp; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("E4",11, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // E3 ::= ENT 
            {
              E RESULT =null;
		TokenValue value = (TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new Num(value.lexema); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("E3",10, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // E3 ::= TRUE 
            {
              E RESULT =null;
		 RESULT = new BoolValue("true"); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("E3",10, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // E3 ::= FALSE 
            {
              E RESULT =null;
		 RESULT = new BoolValue("false"); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("E3",10, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // E3 ::= IDEN 
            {
              E RESULT =null;
		TokenValue id = (TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new Identificador(id.lexema); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("E3",10, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // E3 ::= PAP E0 PCIERRE 
            {
              E RESULT =null;
		E exp = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		 RESULT = exp; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("E3",10, RESULT);
            }
          return CUP$ConstructorAST$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ConstructorAST$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ConstructorAST$do_action(
    int                        CUP$ConstructorAST$act_num,
    java_cup.runtime.lr_parser CUP$ConstructorAST$parser,
    java.util.Stack            CUP$ConstructorAST$stack,
    int                        CUP$ConstructorAST$top)
    throws java.lang.Exception
    {
              return CUP$ConstructorAST$do_action_part00000000(
                               CUP$ConstructorAST$act_num,
                               CUP$ConstructorAST$parser,
                               CUP$ConstructorAST$stack,
                               CUP$ConstructorAST$top);
    }
}

