
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Wed Nov 05 17:10:06 CET 2025
//----------------------------------------------------

package constructorast;

import java_cup.runtime.*;
import alex.AnalizadorLexicoTiny;
import alex.UnidadLexica;
import alex.TokenValue;
import errors.GestionErroresTiny;
import ast.*;
import java.util.LinkedList;
import java_cup.runtime.ComplexSymbolFactory.Location;

/** CUP v0.11b beta 20140220 generated parser.
  * @version Wed Nov 05 17:10:06 CET 2025
  */
public class ConstructorAST extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public ConstructorAST() {super();}

  /** Constructor which sets the default scanner. */
  public ConstructorAST(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ConstructorAST(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\027\000\002\002\003\000\002\002\004\000\002\003" +
    "\004\000\002\003\002\000\002\005\003\000\002\005\003" +
    "\000\002\005\003\000\002\007\006\000\002\010\005\000" +
    "\002\010\005\000\002\006\012\000\002\004\006\000\002" +
    "\011\005\000\002\011\003\000\002\012\005\000\002\012" +
    "\003\000\002\013\005\000\002\013\003\000\002\014\003" +
    "\000\002\014\003\000\002\014\003\000\002\014\003\000" +
    "\002\014\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\057\000\014\002\ufffe\004\012\006\013\011\014\023" +
    "\010\001\002\000\016\002\ufffd\004\ufffd\006\ufffd\011\ufffd" +
    "\021\ufffd\023\ufffd\001\002\000\016\002\ufffc\004\ufffc\006" +
    "\ufffc\011\ufffc\021\ufffc\023\ufffc\001\002\000\016\002\ufffb" +
    "\004\ufffb\006\ufffb\011\ufffb\021\ufffb\023\ufffb\001\002\000" +
    "\004\002\001\001\002\000\004\013\057\001\002\000\004" +
    "\002\056\001\002\000\004\016\023\001\002\000\004\023" +
    "\021\001\002\000\004\023\017\001\002\000\016\002\ufffe" +
    "\004\012\006\013\011\014\021\ufffe\023\010\001\002\000" +
    "\006\002\uffff\021\uffff\001\002\000\004\022\020\001\002" +
    "\000\016\002\ufff8\004\ufff8\006\ufff8\011\ufff8\021\ufff8\023" +
    "\ufff8\001\002\000\004\022\022\001\002\000\016\002\ufff9" +
    "\004\ufff9\006\ufff9\011\ufff9\021\ufff9\023\ufff9\001\002\000" +
    "\014\007\027\010\030\016\025\023\026\024\024\001\002" +
    "\000\014\012\uffef\014\uffef\015\uffef\017\uffef\022\uffef\001" +
    "\002\000\014\007\027\010\030\016\025\023\026\024\024" +
    "\001\002\000\014\012\uffec\014\uffec\015\uffec\017\uffec\022" +
    "\uffec\001\002\000\014\012\uffee\014\uffee\015\uffee\017\uffee" +
    "\022\uffee\001\002\000\014\012\uffed\014\uffed\015\uffed\017" +
    "\uffed\022\uffed\001\002\000\014\012\ufff0\014\ufff0\015\ufff0" +
    "\017\ufff0\022\ufff0\001\002\000\014\012\ufff2\014\052\015" +
    "\ufff2\017\ufff2\022\ufff2\001\002\000\012\012\ufff4\015\050" +
    "\017\ufff4\022\ufff4\001\002\000\006\012\035\017\036\001" +
    "\002\000\014\007\027\010\030\016\025\023\026\024\024" +
    "\001\002\000\004\020\037\001\002\000\014\004\012\006" +
    "\013\011\014\021\ufffe\023\010\001\002\000\004\021\041" +
    "\001\002\000\004\005\042\001\002\000\004\020\044\001" +
    "\002\000\016\002\ufff7\004\ufff7\006\ufff7\011\ufff7\021\ufff7" +
    "\023\ufff7\001\002\000\014\004\012\006\013\011\014\021" +
    "\ufffe\023\010\001\002\000\004\021\046\001\002\000\016" +
    "\002\ufff6\004\ufff6\006\ufff6\011\ufff6\021\ufff6\023\ufff6\001" +
    "\002\000\012\012\ufff5\015\050\017\ufff5\022\ufff5\001\002" +
    "\000\014\007\027\010\030\016\025\023\026\024\024\001" +
    "\002\000\014\012\ufff3\014\052\015\ufff3\017\ufff3\022\ufff3" +
    "\001\002\000\014\007\027\010\030\016\025\023\026\024" +
    "\024\001\002\000\014\012\ufff1\014\ufff1\015\ufff1\017\ufff1" +
    "\022\ufff1\001\002\000\006\012\035\017\055\001\002\000" +
    "\014\012\uffeb\014\uffeb\015\uffeb\017\uffeb\022\uffeb\001\002" +
    "\000\004\002\000\001\002\000\014\007\027\010\030\016" +
    "\025\023\026\024\024\001\002\000\006\012\035\022\061" +
    "\001\002\000\016\002\ufffa\004\ufffa\006\ufffa\011\ufffa\021" +
    "\ufffa\023\ufffa\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\057\000\016\002\010\003\006\005\014\006\003\007" +
    "\004\010\005\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\014\003\015\005\014\006\003\007\004\010" +
    "\005\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\012\011" +
    "\033\012\032\013\031\014\030\001\001\000\002\001\001" +
    "\000\012\011\053\012\032\013\031\014\030\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\012\046\013\031\014\030\001\001\000\002" +
    "\001\001\000\014\003\037\005\014\006\003\007\004\010" +
    "\005\001\001\000\002\001\001\000\004\004\042\001\001" +
    "\000\002\001\001\000\002\001\001\000\014\003\044\005" +
    "\014\006\003\007\004\010\005\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\013\050\014" +
    "\030\001\001\000\002\001\001\000\004\014\052\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\012\011\057\012\032\013\031\014\030" +
    "\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ConstructorAST$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ConstructorAST$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ConstructorAST$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {
 
   errores = new GestionErroresTiny();
   AnalizadorLexicoTiny alex = (AnalizadorLexicoTiny)getScanner();
   alex.fijaGestionErrores(errores);

    }

  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {
 return getScanner().next_token(); 
    }

 
   private GestionErroresTiny errores;
   public void syntax_error(Symbol unidadLexica) {
     errores.errorSintactico((UnidadLexica)unidadLexica);
   }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$ConstructorAST$actions {
  private final ConstructorAST parser;

  /** Constructor */
  CUP$ConstructorAST$actions(ConstructorAST parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ConstructorAST$do_action_part00000000(
    int                        CUP$ConstructorAST$act_num,
    java_cup.runtime.lr_parser CUP$ConstructorAST$parser,
    java.util.Stack            CUP$ConstructorAST$stack,
    int                        CUP$ConstructorAST$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ConstructorAST$result;

      /* select the action based on the action number */
      switch (CUP$ConstructorAST$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // P ::= LInst 
            {
              LinkedList<Instruccion> RESULT =null;
		LinkedList<Instruccion> l = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = l; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("P",0, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= P EOF 
            {
              Object RESULT =null;
		LinkedList<Instruccion> start_val = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		RESULT = start_val;
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("$START",0, RESULT);
            }
          /* ACCEPT */
          CUP$ConstructorAST$parser.done_parsing();
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // LInst ::= Inst LInst 
            {
              LinkedList<Instruccion> RESULT =null;
		Instruccion inst = (Instruccion)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		LinkedList<Instruccion> l = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 l.addFirst(inst);
               RESULT = l;
            
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("LInst",1, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // LInst ::= 
            {
              LinkedList<Instruccion> RESULT =null;
		 RESULT = new LinkedList(); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("LInst",1, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // Inst ::= Cond 
            {
              Instruccion RESULT =null;
		Instruccion inst = (Instruccion)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = inst; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Inst",3, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // Inst ::= Asig 
            {
              Instruccion RESULT =null;
		Instruccion inst = (Instruccion)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = inst; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Inst",3, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // Inst ::= Decl 
            {
              Instruccion RESULT =null;
		Instruccion inst = (Instruccion)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = inst; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Inst",3, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // Asig ::= IDEN IGUAL E0 PUNTOCOMA 
            {
              Instruccion RESULT =null;
		TokenValue id = (TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-3)).value;
		E exp = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		 RESULT = new Asignacion(id.lexema, exp); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Asig",5, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // Decl ::= TIPO_ENT IDEN PUNTOCOMA 
            {
              Instruccion RESULT =null;
		TokenValue id = (TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		 RESULT = new Declaracion(Type.NUM, id.lexema); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Decl",6, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // Decl ::= TIPO_BOOL IDEN PUNTOCOMA 
            {
              Instruccion RESULT =null;
		TokenValue id = (TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		 RESULT = new Declaracion(Type.BOOL, id.lexema); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Decl",6, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // Cond ::= IF PAP E0 PCIERRE CAP LInst CCIERRE ElseCase 
            {
              Instruccion RESULT =null;
		E exp = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-5)).value;
		LinkedList<Instruccion> inst_if = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		LinkedList<Instruccion> inst_else = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new Condicional(exp, inst_if, inst_else); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("Cond",4, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // ElseCase ::= ELSE CAP LInst CCIERRE 
            {
              LinkedList<Instruccion> RESULT =null;
		LinkedList<Instruccion> l = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		 RESULT = l; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("ElseCase",2, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // E0 ::= E0 MAS E1 
            {
              E RESULT =null;
		E op1 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		E op2 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new EBin(BinOps.MAS, op1, op2); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("E0",7, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // E0 ::= E1 
            {
              E RESULT =null;
		E exp = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = exp; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("E0",7, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // E1 ::= E1 MAYOR E2 
            {
              E RESULT =null;
		E op1 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		E op2 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new EBin(BinOps.MAYOR, op1, op2); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("E1",8, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // E1 ::= E2 
            {
              E RESULT =null;
		E exp = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = exp; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("E1",8, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // E2 ::= E2 IGUALIGUAL E3 
            {
              E RESULT =null;
		E op1 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-2)).value;
		E op2 = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new EBin(BinOps.IGUAL, op1, op2); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("E2",9, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // E2 ::= E3 
            {
              E RESULT =null;
		E exp = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = exp; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("E2",9, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // E3 ::= ENT 
            {
              E RESULT =null;
		TokenValue value = (TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new Num(value.lexema); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("E3",10, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // E3 ::= TRUE 
            {
              E RESULT =null;
		 RESULT = new BoolValue("true"); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("E3",10, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // E3 ::= FALSE 
            {
              E RESULT =null;
		 RESULT = new BoolValue("false"); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("E3",10, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // E3 ::= IDEN 
            {
              E RESULT =null;
		TokenValue id = (TokenValue)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.peek()).value;
		 RESULT = new Identificador(id.lexema); 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("E3",10, RESULT);
            }
          return CUP$ConstructorAST$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // E3 ::= PAP E0 PCIERRE 
            {
              E RESULT =null;
		E exp = (E)((java_cup.runtime.Symbol) CUP$ConstructorAST$stack.elementAt(CUP$ConstructorAST$top-1)).value;
		 RESULT = exp; 
              CUP$ConstructorAST$result = parser.getSymbolFactory().newSymbol("E3",10, RESULT);
            }
          return CUP$ConstructorAST$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ConstructorAST$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ConstructorAST$do_action(
    int                        CUP$ConstructorAST$act_num,
    java_cup.runtime.lr_parser CUP$ConstructorAST$parser,
    java.util.Stack            CUP$ConstructorAST$stack,
    int                        CUP$ConstructorAST$top)
    throws java.lang.Exception
    {
              return CUP$ConstructorAST$do_action_part00000000(
                               CUP$ConstructorAST$act_num,
                               CUP$ConstructorAST$parser,
                               CUP$ConstructorAST$stack,
                               CUP$ConstructorAST$top);
    }
}

