
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Thu Oct 30 10:55:54 CET 2025
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int PCIERRE = 15;
  public static final int IGUALIGUAL = 12;
  public static final int ELSE = 3;
  public static final int IGUAL = 11;
  public static final int MULTIPLICA = 19;
  public static final int TIPO_HUGEHUGE = 21;
  public static final int TIPO_HUGE = 20;
  public static final int IDEN = 4;
  public static final int CCIERRE = 17;
  public static final int TRUE = 7;
  public static final int IF = 2;
  public static final int CAP = 16;
  public static final int MAYOR = 13;
  public static final int EOF = 0;
  public static final int TIPO_BOOL = 9;
  public static final int PAP = 14;
  public static final int FALSE = 8;
  public static final int error = 1;
  public static final int TIPO_ENT = 6;
  public static final int PUNTOCOMA = 18;
  public static final int ENT = 5;
  public static final int MAS = 10;
}

